// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/gardener/gardener-extension-provider-azure/pkg/azure/client (interfaces: Factory)

// Package factory is a generated GoMock package.
package factory

import (
	context "context"
	reflect "reflect"

	client "github.com/gardener/gardener-extension-provider-azure/pkg/azure/client"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// DNSRecordSet mocks base method.
func (m *MockFactory) DNSRecordSet(arg0 context.Context, arg1 v1.SecretReference) (client.DNSRecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DNSRecordSet", arg0, arg1)
	ret0, _ := ret[0].(client.DNSRecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DNSRecordSet indicates an expected call of DNSRecordSet.
func (mr *MockFactoryMockRecorder) DNSRecordSet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSRecordSet", reflect.TypeOf((*MockFactory)(nil).DNSRecordSet), arg0, arg1)
}

// DNSZone mocks base method.
func (m *MockFactory) DNSZone(arg0 context.Context, arg1 v1.SecretReference) (client.DNSZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DNSZone", arg0, arg1)
	ret0, _ := ret[0].(client.DNSZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DNSZone indicates an expected call of DNSZone.
func (mr *MockFactoryMockRecorder) DNSZone(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DNSZone", reflect.TypeOf((*MockFactory)(nil).DNSZone), arg0, arg1)
}

// Disk mocks base method.
func (m *MockFactory) Disk(arg0 context.Context, arg1 v1.SecretReference) (client.Disk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disk", arg0, arg1)
	ret0, _ := ret[0].(client.Disk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disk indicates an expected call of Disk.
func (mr *MockFactoryMockRecorder) Disk(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disk", reflect.TypeOf((*MockFactory)(nil).Disk), arg0, arg1)
}

// Group mocks base method.
func (m *MockFactory) Group(arg0 context.Context, arg1 v1.SecretReference) (client.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Group", arg0, arg1)
	ret0, _ := ret[0].(client.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Group indicates an expected call of Group.
func (mr *MockFactoryMockRecorder) Group(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockFactory)(nil).Group), arg0, arg1)
}

// NetworkInterface mocks base method.
func (m *MockFactory) NetworkInterface(arg0 context.Context, arg1 v1.SecretReference) (client.NetworkInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkInterface", arg0, arg1)
	ret0, _ := ret[0].(client.NetworkInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkInterface indicates an expected call of NetworkInterface.
func (mr *MockFactoryMockRecorder) NetworkInterface(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkInterface", reflect.TypeOf((*MockFactory)(nil).NetworkInterface), arg0, arg1)
}

// NetworkSecurityGroup mocks base method.
func (m *MockFactory) NetworkSecurityGroup(arg0 context.Context, arg1 v1.SecretReference) (client.NetworkSecurityGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NetworkSecurityGroup", arg0, arg1)
	ret0, _ := ret[0].(client.NetworkSecurityGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NetworkSecurityGroup indicates an expected call of NetworkSecurityGroup.
func (mr *MockFactoryMockRecorder) NetworkSecurityGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NetworkSecurityGroup", reflect.TypeOf((*MockFactory)(nil).NetworkSecurityGroup), arg0, arg1)
}

// PublicIP mocks base method.
func (m *MockFactory) PublicIP(arg0 context.Context, arg1 v1.SecretReference) (client.PublicIP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicIP", arg0, arg1)
	ret0, _ := ret[0].(client.PublicIP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicIP indicates an expected call of PublicIP.
func (mr *MockFactoryMockRecorder) PublicIP(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicIP", reflect.TypeOf((*MockFactory)(nil).PublicIP), arg0, arg1)
}

// Storage mocks base method.
func (m *MockFactory) Storage(arg0 context.Context, arg1 v1.SecretReference) (client.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Storage", arg0, arg1)
	ret0, _ := ret[0].(client.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Storage indicates an expected call of Storage.
func (mr *MockFactoryMockRecorder) Storage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Storage", reflect.TypeOf((*MockFactory)(nil).Storage), arg0, arg1)
}

// StorageAccount mocks base method.
func (m *MockFactory) StorageAccount(arg0 context.Context, arg1 v1.SecretReference) (client.StorageAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageAccount", arg0, arg1)
	ret0, _ := ret[0].(client.StorageAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageAccount indicates an expected call of StorageAccount.
func (mr *MockFactoryMockRecorder) StorageAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageAccount", reflect.TypeOf((*MockFactory)(nil).StorageAccount), arg0, arg1)
}

// Subnet mocks base method.
func (m *MockFactory) Subnet(arg0 context.Context, arg1 v1.SecretReference) (client.Subnet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subnet", arg0, arg1)
	ret0, _ := ret[0].(client.Subnet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subnet indicates an expected call of Subnet.
func (mr *MockFactoryMockRecorder) Subnet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subnet", reflect.TypeOf((*MockFactory)(nil).Subnet), arg0, arg1)
}

// VirtualMachine mocks base method.
func (m *MockFactory) VirtualMachine(arg0 context.Context, arg1 v1.SecretReference) (client.VirtualMachine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VirtualMachine", arg0, arg1)
	ret0, _ := ret[0].(client.VirtualMachine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VirtualMachine indicates an expected call of VirtualMachine.
func (mr *MockFactoryMockRecorder) VirtualMachine(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VirtualMachine", reflect.TypeOf((*MockFactory)(nil).VirtualMachine), arg0, arg1)
}

// Vmss mocks base method.
func (m *MockFactory) Vmss(arg0 context.Context, arg1 v1.SecretReference) (client.Vmss, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vmss", arg0, arg1)
	ret0, _ := ret[0].(client.Vmss)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Vmss indicates an expected call of Vmss.
func (mr *MockFactoryMockRecorder) Vmss(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vmss", reflect.TypeOf((*MockFactory)(nil).Vmss), arg0, arg1)
}
