---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--azure
type: Opaque
data:
  clientID: ZGF0YQo=
  clientSecret: ZGF0YQo=
  subscriptionID: ZGF0YQo=
  tenantID: ZGF0YQo=
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--azure
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
    spec:
      providerConfig:
        apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
        kind: CloudProfileConfig
        machineImages:
          - name: coreos
            versions:
              - version: 2135.6.0
                urn: azureimageurn
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    spec:
      kubernetes:
        version: 1.28.2
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keypair
  namespace: shoot--foobar--azure
type: Opaque
data:
  id_rsa.pub: dGhlLXNzaC1rZXktZm9yLXRoZS1tYWNoaW5l
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# provided infrastructure status data (subnet id, etc.) is not valid/does not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foobar--azure
  annotations:
    gardener.cloud/operation: reconcile
spec:
  type: azure
  region: westeurope
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--azure
  infrastructureProviderStatus:
    apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    resourceGroup:
      name: my-resource-group
    networks:
      vnet:
        name: my-vnet
      subnets:
      - purpose: nodes
        name: subnet-123
    availabilitySets:
    - purpose: nodes
      id: av-nodes-1234-id
      name: av-nodes-1234-name
    routeTables:
    - purpose: nodes
      name: route-table-1
    securityGroups:
    - purpose: nodes
      name: sec-group-1
  pools:
  - name: cpu-worker
    machineType: Standard_D2_v3
    machineImage:
      name: coreos
      version: 2135.6.0
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
  # labels:
  #   key: value
  # annotations:
  #   key: value
  # taints: # See also https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # - key: foo
  #   value: bar
  #   effect: NoSchedule
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    volume:
      type: standard
      size: 35Gi
  # dataVolumes:
  # - name: kubelet-dir
  #   type: standard
  #   size: 36Gi
  # providerConfig:
  #   apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
  #   kind: WorkerConfig
  #   diagnosticsProfile:
  #     enabled: false
  #     storageURI: https://<storage-account-name>.blob.core.windows.net/
