---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: disk.csi.azure.com
  annotations:
    resources.gardener.cloud/delete-on-invalid-update: "true"
spec:
  attachRequired: true
  podInfoOnMount: false
  fsGroupPolicy: File
