---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "csi-driver-node.extensionsGroup" . }}.{{ include "csi-driver-node.name" . }}.csi-driver-node
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
  - hostPath
  - projected
  - secret
  - configMap
  hostNetwork: true
  hostPorts:
  - max: 29605
    min: 29603
  - max: 29615
    min: 29613
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet
  - pathPrefix: /dev
  - pathPrefix: /var/lib/waagent
  - pathPrefix: /sys/bus/scsi/devices
  - pathPrefix: /sys/class/scsi_host
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: false
