azure:
  region: westeurope
  countUpdateDomains: 5
  countFaultDomains: 2

create:
  resourceGroup: true
  vnet: true
  availabilitySet: false
  natGateway: false

# identity:
  # name: identity-name
  # resourceGroup: identity-resource-group

# natGateway:
  # idleConnectionTimeoutMinutes: 4
  # zone: 1
  # migrateNatGatewayToIPAssociation: false # TODO(natipmigration) This can be removed in future versions when the ip migration has been completed.
  # ipAddresses:
  # - name: public-ip-0-name
  #   resourceGroup: public-ip-0-resource-group
  # - name: public-ip-1-name
  #   resourceGroup: public-ip-1-resource-group

resourceGroup:
  name: my-resource-group
  vnet:
    name: my-vnet
    # resourceGroup: vnet-resource-group
    cidr: 10.10.10.10/6
  subnet:
    serviceEndpoints: []

clusterName: test-namespace

networks:
  worker: 10.250.0.0/19

outputKeys:
  resourceGroupName: resourceGroupName
  vnetName: vnetName
  # vnetResourceGroup: vnet-resource-group
  subnetName: subnetName
  availabilitySetID: availabilitySetID
  availabilitySetName: availabilitySetName
  countFaultDomains: countFaultDomains
  countUpdateDomains: countUpdateDomains
  routeTableName: routeTableName
  securityGroupName: securityGroupName
  # identityID: managedIdentityID
  # identityClientID: managedIdentityClientID
