apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: provider-azure
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-azure-runtime:v1.54.2
      virtualCluster:
        helm:
          ociRepository:
            ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/admission-azure-application:v1.54.2
    extension:
      helm:
        ociRepository:
          ref: europe-docker.pkg.dev/gardener-project/public/charts/gardener/extensions/provider-azure:v1.54.2
      injectGardenKubeconfig: true
  resources:
  - kind: BackupBucket
    type: azure
  - kind: BackupEntry
    type: azure
  - kind: Bastion
    type: azure
  - kind: ControlPlane
    type: azure
  - kind: DNSRecord
    type: azure
  - kind: Infrastructure
    type: azure
  - kind: Worker
    type: azure
