{
 "title": "Remedy Controller",
 "tags": [
  "controlplane",
  "seed"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Controller",
    "query": "service, node, publicipaddress, virtualmachine"
   }
  ]
 },
 "panels": [
  {
   "title": "Cleaned Azure IP Addresses",
   "type": "graph",
   "description": "Cleaned Azure public IP addresses",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cleaned_azure_public_ips_total", "legendFormat": "({{pod}})" }
   ]
  },
  {
   "title": "Reapplied Azure Virtual Machines",
   "type": "graph",
   "description": "Reapplied Azure virtual machines",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "reapplied_azure_virtual_machines_total",
     "legendFormat": "({{pod}})"
    }
   ]
  },
  {
   "title": "Azure Virtual Machine States",
   "type": "graph",
   "description": "Azure virtual machine states.\n\n| Code | State |\n|---|---|\n| 0 | OK |\n| 1 | Failed, trying to fix |\n| 2 | Failed |",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "azure_virtual_machine_states", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Azure Requests",
   "type": "graph",
   "description": "Average per second rate over 5m of Azure read and write requests",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(azure_read_requests_total[5m])",
     "legendFormat": "read ({{pod}})"
    },
    {
     "expr": "rate(azure_write_requests_total[5m])",
     "legendFormat": "write ({{pod}})"
    }
   ]
  },
  {
   "title": "Remedy Controller Memory Usage",
   "type": "graph",
   "description": "Memory usage of the remedy controller",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"remedy-controller-azure-(.+)\",job=\"kube-kubelet-seed\"}",
     "legendFormat": "current ({{pod}})"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"remedy-controller-azure-(.+)\",job=\"kube-kubelet-seed\"}",
     "legendFormat": "limits ({{pod}})"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"remedy-controller-azure-(.+)\",job=\"kube-kubelet-seed\"}",
     "legendFormat": "requests ({{pod}})"
    }
   ]
  },
  {
   "title": "Remedy Controller CPU Usage",
   "type": "graph",
   "description": "CPU usage, requests, and limits of the remedy controller",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"remedy-controller-azure-(.+)\",job=\"kube-kubelet-seed\"}[5m])",
     "legendFormat": "current ({{pod}})"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"remedy-controller-azure-(.+)\",job=\"kube-kubelet-seed\"}",
     "legendFormat": "limits ({{pod}})"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"remedy-controller-azure-(.+)\",job=\"kube-kubelet-seed\"}",
     "legendFormat": "requests ({{pod}})"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Requests",
   "type": "graph",
   "description": "Average per second rate over 5m of requests to cluster API server, split by response status codes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{host=~\".*kube-apiserver.*\", job=\"remedy-controller-azure\"}[5m])) by(code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Remedy Controllers UP",
   "type": "singlestat",
   "description": "Current uptime status of the remedy controllers.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"remedy-controller-azure\"} == 1) / sum(up{job=\"kube-controller-manager\"})) * 100"
    }
   ]
  },
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Workqueue Work Duration: ${name}",
   "type": "graph",
   "description": "Aggregate per second rate over 5m of how long in seconds processing an item from workqueue takes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket{name=\"azure${name}-controller\"}[5m])) by (le,pod))",
     "legendFormat": "p50 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket{name=\"azure${name}-controller\"}[5m])) by (le,pod))",
     "legendFormat": "p90 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{name=\"azure${name}-controller\"}[5m])) by (le,pod))",
     "legendFormat": "p99 ({{pod}})"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration: ${name}",
   "type": "graph",
   "description": "Aggregate per second rate over 5m of how long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket{name=\"azure${name}-controller\"}[5m])) by (le,pod))",
     "legendFormat": "p50 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_queue_duration_seconds_bucket{name=\"azure${name}-controller\"}[5m])) by (le,pod))",
     "legendFormat": "p90 ({{pod}})"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{name=\"azure${name}-controller\"}[5m])) by (le,pod))",
     "legendFormat": "p99 ({{pod}})"
    }
   ]
  },
  {
   "title": "Workqueue Depth: ${name}",
   "type": "graph",
   "description": "Current depth of workqueue",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "workqueue_depth{name=\"azure${name}-controller\"}",
     "legendFormat": "({{pod}})"
    }
   ]
  },
  {
   "title": "Workqueue Adds: ${name}",
   "type": "graph",
   "description": "Average per second rate over 5m of workqueue item adds",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_adds_total{name=\"azure${name}-controller\"}[5m])",
     "legendFormat": "({{pod}})"
    }
   ]
  },
  {
   "title": "Workqueue Retries: ${name}",
   "type": "graph",
   "description": "Average per second rate over 5m of workqueue item retries.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workqueue_retries_total{name=\"azure${name}-controller\"}[5m])",
     "legendFormat": "({{pod}})"
    }
   ]
  }
 ]
}