//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	azure "github.com/gardener/gardener-extension-provider-azure/pkg/apis/azure"
	extensionsv1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AvailabilitySet)(nil), (*azure.AvailabilitySet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AvailabilitySet_To_azure_AvailabilitySet(a.(*AvailabilitySet), b.(*azure.AvailabilitySet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.AvailabilitySet)(nil), (*AvailabilitySet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_AvailabilitySet_To_v1alpha1_AvailabilitySet(a.(*azure.AvailabilitySet), b.(*AvailabilitySet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AzureResource)(nil), (*azure.AzureResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AzureResource_To_azure_AzureResource(a.(*AzureResource), b.(*azure.AzureResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.AzureResource)(nil), (*AzureResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_AzureResource_To_v1alpha1_AzureResource(a.(*azure.AzureResource), b.(*AzureResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BackupBucketConfig)(nil), (*azure.BackupBucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BackupBucketConfig_To_azure_BackupBucketConfig(a.(*BackupBucketConfig), b.(*azure.BackupBucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.BackupBucketConfig)(nil), (*BackupBucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(a.(*azure.BackupBucketConfig), b.(*BackupBucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudConfiguration)(nil), (*azure.CloudConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudConfiguration_To_azure_CloudConfiguration(a.(*CloudConfiguration), b.(*azure.CloudConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.CloudConfiguration)(nil), (*CloudConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_CloudConfiguration_To_v1alpha1_CloudConfiguration(a.(*azure.CloudConfiguration), b.(*CloudConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*azure.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_azure_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*azure.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*azure.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*azure.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_azure_CloudProfileConfig(a.(*CloudProfileConfig), b.(*azure.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*azure.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*azure.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_azure_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*azure.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*azure.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataVolume)(nil), (*azure.DataVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DataVolume_To_azure_DataVolume(a.(*DataVolume), b.(*azure.DataVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.DataVolume)(nil), (*DataVolume)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_DataVolume_To_v1alpha1_DataVolume(a.(*azure.DataVolume), b.(*DataVolume), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiagnosticsProfile)(nil), (*azure.DiagnosticsProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiagnosticsProfile_To_azure_DiagnosticsProfile(a.(*DiagnosticsProfile), b.(*azure.DiagnosticsProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.DiagnosticsProfile)(nil), (*DiagnosticsProfile)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_DiagnosticsProfile_To_v1alpha1_DiagnosticsProfile(a.(*azure.DiagnosticsProfile), b.(*DiagnosticsProfile), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DomainCount)(nil), (*azure.DomainCount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DomainCount_To_azure_DomainCount(a.(*DomainCount), b.(*azure.DomainCount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.DomainCount)(nil), (*DomainCount)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_DomainCount_To_v1alpha1_DomainCount(a.(*azure.DomainCount), b.(*DomainCount), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IdentityConfig)(nil), (*azure.IdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IdentityConfig_To_azure_IdentityConfig(a.(*IdentityConfig), b.(*azure.IdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.IdentityConfig)(nil), (*IdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_IdentityConfig_To_v1alpha1_IdentityConfig(a.(*azure.IdentityConfig), b.(*IdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*IdentityStatus)(nil), (*azure.IdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_IdentityStatus_To_azure_IdentityStatus(a.(*IdentityStatus), b.(*azure.IdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.IdentityStatus)(nil), (*IdentityStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_IdentityStatus_To_v1alpha1_IdentityStatus(a.(*azure.IdentityStatus), b.(*IdentityStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Image)(nil), (*azure.Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Image_To_azure_Image(a.(*Image), b.(*azure.Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Image)(nil), (*Image)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Image_To_v1alpha1_Image(a.(*azure.Image), b.(*Image), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*azure.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_azure_InfrastructureConfig(a.(*InfrastructureConfig), b.(*azure.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*azure.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureState)(nil), (*azure.InfrastructureState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureState_To_azure_InfrastructureState(a.(*InfrastructureState), b.(*azure.InfrastructureState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.InfrastructureState)(nil), (*InfrastructureState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_InfrastructureState_To_v1alpha1_InfrastructureState(a.(*azure.InfrastructureState), b.(*InfrastructureState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*azure.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_azure_InfrastructureStatus(a.(*InfrastructureStatus), b.(*azure.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*azure.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*azure.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_azure_MachineImage(a.(*MachineImage), b.(*azure.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_MachineImage_To_v1alpha1_MachineImage(a.(*azure.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*azure.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_azure_MachineImageVersion(a.(*MachineImageVersion), b.(*azure.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*azure.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*azure.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_azure_MachineImages(a.(*MachineImages), b.(*azure.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_MachineImages_To_v1alpha1_MachineImages(a.(*azure.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineType)(nil), (*azure.MachineType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineType_To_azure_MachineType(a.(*MachineType), b.(*azure.MachineType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.MachineType)(nil), (*MachineType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_MachineType_To_v1alpha1_MachineType(a.(*azure.MachineType), b.(*MachineType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NatGatewayConfig)(nil), (*azure.NatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NatGatewayConfig_To_azure_NatGatewayConfig(a.(*NatGatewayConfig), b.(*azure.NatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.NatGatewayConfig)(nil), (*NatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(a.(*azure.NatGatewayConfig), b.(*NatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkConfig)(nil), (*azure.NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkConfig_To_azure_NetworkConfig(a.(*NetworkConfig), b.(*azure.NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.NetworkConfig)(nil), (*NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_NetworkConfig_To_v1alpha1_NetworkConfig(a.(*azure.NetworkConfig), b.(*NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*azure.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_azure_NetworkStatus(a.(*NetworkStatus), b.(*azure.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*azure.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PublicIPReference)(nil), (*azure.PublicIPReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PublicIPReference_To_azure_PublicIPReference(a.(*PublicIPReference), b.(*azure.PublicIPReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.PublicIPReference)(nil), (*PublicIPReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_PublicIPReference_To_v1alpha1_PublicIPReference(a.(*azure.PublicIPReference), b.(*PublicIPReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceGroup)(nil), (*azure.ResourceGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceGroup_To_azure_ResourceGroup(a.(*ResourceGroup), b.(*azure.ResourceGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.ResourceGroup)(nil), (*ResourceGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_ResourceGroup_To_v1alpha1_ResourceGroup(a.(*azure.ResourceGroup), b.(*ResourceGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RouteTable)(nil), (*azure.RouteTable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RouteTable_To_azure_RouteTable(a.(*RouteTable), b.(*azure.RouteTable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.RouteTable)(nil), (*RouteTable)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_RouteTable_To_v1alpha1_RouteTable(a.(*azure.RouteTable), b.(*RouteTable), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecurityGroup)(nil), (*azure.SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecurityGroup_To_azure_SecurityGroup(a.(*SecurityGroup), b.(*azure.SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.SecurityGroup)(nil), (*SecurityGroup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_SecurityGroup_To_v1alpha1_SecurityGroup(a.(*azure.SecurityGroup), b.(*SecurityGroup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*azure.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_azure_Storage(a.(*Storage), b.(*azure.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Storage_To_v1alpha1_Storage(a.(*azure.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Subnet)(nil), (*azure.Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Subnet_To_azure_Subnet(a.(*Subnet), b.(*azure.Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Subnet)(nil), (*Subnet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Subnet_To_v1alpha1_Subnet(a.(*azure.Subnet), b.(*Subnet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VNet)(nil), (*azure.VNet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VNet_To_azure_VNet(a.(*VNet), b.(*azure.VNet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.VNet)(nil), (*VNet)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_VNet_To_v1alpha1_VNet(a.(*azure.VNet), b.(*VNet), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VNetStatus)(nil), (*azure.VNetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VNetStatus_To_azure_VNetStatus(a.(*VNetStatus), b.(*azure.VNetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.VNetStatus)(nil), (*VNetStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_VNetStatus_To_v1alpha1_VNetStatus(a.(*azure.VNetStatus), b.(*VNetStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VmoDependency)(nil), (*azure.VmoDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VmoDependency_To_azure_VmoDependency(a.(*VmoDependency), b.(*azure.VmoDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.VmoDependency)(nil), (*VmoDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_VmoDependency_To_v1alpha1_VmoDependency(a.(*azure.VmoDependency), b.(*VmoDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerConfig)(nil), (*azure.WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerConfig_To_azure_WorkerConfig(a.(*WorkerConfig), b.(*azure.WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.WorkerConfig)(nil), (*WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_WorkerConfig_To_v1alpha1_WorkerConfig(a.(*azure.WorkerConfig), b.(*WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*azure.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_azure_WorkerStatus(a.(*WorkerStatus), b.(*azure.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*azure.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentityConfig)(nil), (*azure.WorkloadIdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkloadIdentityConfig_To_azure_WorkloadIdentityConfig(a.(*WorkloadIdentityConfig), b.(*azure.WorkloadIdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.WorkloadIdentityConfig)(nil), (*WorkloadIdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(a.(*azure.WorkloadIdentityConfig), b.(*WorkloadIdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Zone)(nil), (*azure.Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Zone_To_azure_Zone(a.(*Zone), b.(*azure.Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.Zone)(nil), (*Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_Zone_To_v1alpha1_Zone(a.(*azure.Zone), b.(*Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ZonedNatGatewayConfig)(nil), (*azure.ZonedNatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ZonedNatGatewayConfig_To_azure_ZonedNatGatewayConfig(a.(*ZonedNatGatewayConfig), b.(*azure.ZonedNatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.ZonedNatGatewayConfig)(nil), (*ZonedNatGatewayConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_ZonedNatGatewayConfig_To_v1alpha1_ZonedNatGatewayConfig(a.(*azure.ZonedNatGatewayConfig), b.(*ZonedNatGatewayConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ZonedPublicIPReference)(nil), (*azure.ZonedPublicIPReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ZonedPublicIPReference_To_azure_ZonedPublicIPReference(a.(*ZonedPublicIPReference), b.(*azure.ZonedPublicIPReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*azure.ZonedPublicIPReference)(nil), (*ZonedPublicIPReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_azure_ZonedPublicIPReference_To_v1alpha1_ZonedPublicIPReference(a.(*azure.ZonedPublicIPReference), b.(*ZonedPublicIPReference), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AvailabilitySet_To_azure_AvailabilitySet(in *AvailabilitySet, out *azure.AvailabilitySet, s conversion.Scope) error {
	out.Purpose = azure.Purpose(in.Purpose)
	out.ID = in.ID
	out.Name = in.Name
	out.CountFaultDomains = (*int32)(unsafe.Pointer(in.CountFaultDomains))
	out.CountUpdateDomains = (*int32)(unsafe.Pointer(in.CountUpdateDomains))
	return nil
}

// Convert_v1alpha1_AvailabilitySet_To_azure_AvailabilitySet is an autogenerated conversion function.
func Convert_v1alpha1_AvailabilitySet_To_azure_AvailabilitySet(in *AvailabilitySet, out *azure.AvailabilitySet, s conversion.Scope) error {
	return autoConvert_v1alpha1_AvailabilitySet_To_azure_AvailabilitySet(in, out, s)
}

func autoConvert_azure_AvailabilitySet_To_v1alpha1_AvailabilitySet(in *azure.AvailabilitySet, out *AvailabilitySet, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.ID = in.ID
	out.Name = in.Name
	out.CountFaultDomains = (*int32)(unsafe.Pointer(in.CountFaultDomains))
	out.CountUpdateDomains = (*int32)(unsafe.Pointer(in.CountUpdateDomains))
	return nil
}

// Convert_azure_AvailabilitySet_To_v1alpha1_AvailabilitySet is an autogenerated conversion function.
func Convert_azure_AvailabilitySet_To_v1alpha1_AvailabilitySet(in *azure.AvailabilitySet, out *AvailabilitySet, s conversion.Scope) error {
	return autoConvert_azure_AvailabilitySet_To_v1alpha1_AvailabilitySet(in, out, s)
}

func autoConvert_v1alpha1_AzureResource_To_azure_AzureResource(in *AzureResource, out *azure.AzureResource, s conversion.Scope) error {
	out.Kind = in.Kind
	out.ID = in.ID
	return nil
}

// Convert_v1alpha1_AzureResource_To_azure_AzureResource is an autogenerated conversion function.
func Convert_v1alpha1_AzureResource_To_azure_AzureResource(in *AzureResource, out *azure.AzureResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_AzureResource_To_azure_AzureResource(in, out, s)
}

func autoConvert_azure_AzureResource_To_v1alpha1_AzureResource(in *azure.AzureResource, out *AzureResource, s conversion.Scope) error {
	out.Kind = in.Kind
	out.ID = in.ID
	return nil
}

// Convert_azure_AzureResource_To_v1alpha1_AzureResource is an autogenerated conversion function.
func Convert_azure_AzureResource_To_v1alpha1_AzureResource(in *azure.AzureResource, out *AzureResource, s conversion.Scope) error {
	return autoConvert_azure_AzureResource_To_v1alpha1_AzureResource(in, out, s)
}

func autoConvert_v1alpha1_BackupBucketConfig_To_azure_BackupBucketConfig(in *BackupBucketConfig, out *azure.BackupBucketConfig, s conversion.Scope) error {
	out.CloudConfiguration = (*azure.CloudConfiguration)(unsafe.Pointer(in.CloudConfiguration))
	return nil
}

// Convert_v1alpha1_BackupBucketConfig_To_azure_BackupBucketConfig is an autogenerated conversion function.
func Convert_v1alpha1_BackupBucketConfig_To_azure_BackupBucketConfig(in *BackupBucketConfig, out *azure.BackupBucketConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_BackupBucketConfig_To_azure_BackupBucketConfig(in, out, s)
}

func autoConvert_azure_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in *azure.BackupBucketConfig, out *BackupBucketConfig, s conversion.Scope) error {
	out.CloudConfiguration = (*CloudConfiguration)(unsafe.Pointer(in.CloudConfiguration))
	return nil
}

// Convert_azure_BackupBucketConfig_To_v1alpha1_BackupBucketConfig is an autogenerated conversion function.
func Convert_azure_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in *azure.BackupBucketConfig, out *BackupBucketConfig, s conversion.Scope) error {
	return autoConvert_azure_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudConfiguration_To_azure_CloudConfiguration(in *CloudConfiguration, out *azure.CloudConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_CloudConfiguration_To_azure_CloudConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_CloudConfiguration_To_azure_CloudConfiguration(in *CloudConfiguration, out *azure.CloudConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudConfiguration_To_azure_CloudConfiguration(in, out, s)
}

func autoConvert_azure_CloudConfiguration_To_v1alpha1_CloudConfiguration(in *azure.CloudConfiguration, out *CloudConfiguration, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_azure_CloudConfiguration_To_v1alpha1_CloudConfiguration is an autogenerated conversion function.
func Convert_azure_CloudConfiguration_To_v1alpha1_CloudConfiguration(in *azure.CloudConfiguration, out *CloudConfiguration, s conversion.Scope) error {
	return autoConvert_azure_CloudConfiguration_To_v1alpha1_CloudConfiguration(in, out, s)
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_azure_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *azure.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_azure_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_azure_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *azure.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_azure_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_azure_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *azure.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_azure_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_azure_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *azure.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_azure_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_azure_CloudProfileConfig(in *CloudProfileConfig, out *azure.CloudProfileConfig, s conversion.Scope) error {
	out.CountUpdateDomains = *(*[]azure.DomainCount)(unsafe.Pointer(&in.CountUpdateDomains))
	out.CountFaultDomains = *(*[]azure.DomainCount)(unsafe.Pointer(&in.CountFaultDomains))
	out.MachineImages = *(*[]azure.MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.MachineTypes = *(*[]azure.MachineType)(unsafe.Pointer(&in.MachineTypes))
	out.CloudConfiguration = (*azure.CloudConfiguration)(unsafe.Pointer(in.CloudConfiguration))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_azure_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_azure_CloudProfileConfig(in *CloudProfileConfig, out *azure.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_azure_CloudProfileConfig(in, out, s)
}

func autoConvert_azure_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *azure.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.CountUpdateDomains = *(*[]DomainCount)(unsafe.Pointer(&in.CountUpdateDomains))
	out.CountFaultDomains = *(*[]DomainCount)(unsafe.Pointer(&in.CountFaultDomains))
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.MachineTypes = *(*[]MachineType)(unsafe.Pointer(&in.MachineTypes))
	out.CloudConfiguration = (*CloudConfiguration)(unsafe.Pointer(in.CloudConfiguration))
	return nil
}

// Convert_azure_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_azure_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *azure.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_azure_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_azure_ControlPlaneConfig(in *ControlPlaneConfig, out *azure.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*azure.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.Storage = (*azure.Storage)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_azure_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_azure_ControlPlaneConfig(in *ControlPlaneConfig, out *azure.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_azure_ControlPlaneConfig(in, out, s)
}

func autoConvert_azure_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *azure.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	out.Storage = (*Storage)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_azure_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_azure_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *azure.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_azure_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_DataVolume_To_azure_DataVolume(in *DataVolume, out *azure.DataVolume, s conversion.Scope) error {
	out.Name = in.Name
	out.ImageRef = (*azure.Image)(unsafe.Pointer(in.ImageRef))
	return nil
}

// Convert_v1alpha1_DataVolume_To_azure_DataVolume is an autogenerated conversion function.
func Convert_v1alpha1_DataVolume_To_azure_DataVolume(in *DataVolume, out *azure.DataVolume, s conversion.Scope) error {
	return autoConvert_v1alpha1_DataVolume_To_azure_DataVolume(in, out, s)
}

func autoConvert_azure_DataVolume_To_v1alpha1_DataVolume(in *azure.DataVolume, out *DataVolume, s conversion.Scope) error {
	out.Name = in.Name
	out.ImageRef = (*Image)(unsafe.Pointer(in.ImageRef))
	return nil
}

// Convert_azure_DataVolume_To_v1alpha1_DataVolume is an autogenerated conversion function.
func Convert_azure_DataVolume_To_v1alpha1_DataVolume(in *azure.DataVolume, out *DataVolume, s conversion.Scope) error {
	return autoConvert_azure_DataVolume_To_v1alpha1_DataVolume(in, out, s)
}

func autoConvert_v1alpha1_DiagnosticsProfile_To_azure_DiagnosticsProfile(in *DiagnosticsProfile, out *azure.DiagnosticsProfile, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.StorageURI = (*string)(unsafe.Pointer(in.StorageURI))
	return nil
}

// Convert_v1alpha1_DiagnosticsProfile_To_azure_DiagnosticsProfile is an autogenerated conversion function.
func Convert_v1alpha1_DiagnosticsProfile_To_azure_DiagnosticsProfile(in *DiagnosticsProfile, out *azure.DiagnosticsProfile, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiagnosticsProfile_To_azure_DiagnosticsProfile(in, out, s)
}

func autoConvert_azure_DiagnosticsProfile_To_v1alpha1_DiagnosticsProfile(in *azure.DiagnosticsProfile, out *DiagnosticsProfile, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.StorageURI = (*string)(unsafe.Pointer(in.StorageURI))
	return nil
}

// Convert_azure_DiagnosticsProfile_To_v1alpha1_DiagnosticsProfile is an autogenerated conversion function.
func Convert_azure_DiagnosticsProfile_To_v1alpha1_DiagnosticsProfile(in *azure.DiagnosticsProfile, out *DiagnosticsProfile, s conversion.Scope) error {
	return autoConvert_azure_DiagnosticsProfile_To_v1alpha1_DiagnosticsProfile(in, out, s)
}

func autoConvert_v1alpha1_DomainCount_To_azure_DomainCount(in *DomainCount, out *azure.DomainCount, s conversion.Scope) error {
	out.Region = in.Region
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_DomainCount_To_azure_DomainCount is an autogenerated conversion function.
func Convert_v1alpha1_DomainCount_To_azure_DomainCount(in *DomainCount, out *azure.DomainCount, s conversion.Scope) error {
	return autoConvert_v1alpha1_DomainCount_To_azure_DomainCount(in, out, s)
}

func autoConvert_azure_DomainCount_To_v1alpha1_DomainCount(in *azure.DomainCount, out *DomainCount, s conversion.Scope) error {
	out.Region = in.Region
	out.Count = in.Count
	return nil
}

// Convert_azure_DomainCount_To_v1alpha1_DomainCount is an autogenerated conversion function.
func Convert_azure_DomainCount_To_v1alpha1_DomainCount(in *azure.DomainCount, out *DomainCount, s conversion.Scope) error {
	return autoConvert_azure_DomainCount_To_v1alpha1_DomainCount(in, out, s)
}

func autoConvert_v1alpha1_IdentityConfig_To_azure_IdentityConfig(in *IdentityConfig, out *azure.IdentityConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.ACRAccess = (*bool)(unsafe.Pointer(in.ACRAccess))
	return nil
}

// Convert_v1alpha1_IdentityConfig_To_azure_IdentityConfig is an autogenerated conversion function.
func Convert_v1alpha1_IdentityConfig_To_azure_IdentityConfig(in *IdentityConfig, out *azure.IdentityConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_IdentityConfig_To_azure_IdentityConfig(in, out, s)
}

func autoConvert_azure_IdentityConfig_To_v1alpha1_IdentityConfig(in *azure.IdentityConfig, out *IdentityConfig, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.ACRAccess = (*bool)(unsafe.Pointer(in.ACRAccess))
	return nil
}

// Convert_azure_IdentityConfig_To_v1alpha1_IdentityConfig is an autogenerated conversion function.
func Convert_azure_IdentityConfig_To_v1alpha1_IdentityConfig(in *azure.IdentityConfig, out *IdentityConfig, s conversion.Scope) error {
	return autoConvert_azure_IdentityConfig_To_v1alpha1_IdentityConfig(in, out, s)
}

func autoConvert_v1alpha1_IdentityStatus_To_azure_IdentityStatus(in *IdentityStatus, out *azure.IdentityStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.ClientID = in.ClientID
	out.ACRAccess = in.ACRAccess
	return nil
}

// Convert_v1alpha1_IdentityStatus_To_azure_IdentityStatus is an autogenerated conversion function.
func Convert_v1alpha1_IdentityStatus_To_azure_IdentityStatus(in *IdentityStatus, out *azure.IdentityStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_IdentityStatus_To_azure_IdentityStatus(in, out, s)
}

func autoConvert_azure_IdentityStatus_To_v1alpha1_IdentityStatus(in *azure.IdentityStatus, out *IdentityStatus, s conversion.Scope) error {
	out.ID = in.ID
	out.ClientID = in.ClientID
	out.ACRAccess = in.ACRAccess
	return nil
}

// Convert_azure_IdentityStatus_To_v1alpha1_IdentityStatus is an autogenerated conversion function.
func Convert_azure_IdentityStatus_To_v1alpha1_IdentityStatus(in *azure.IdentityStatus, out *IdentityStatus, s conversion.Scope) error {
	return autoConvert_azure_IdentityStatus_To_v1alpha1_IdentityStatus(in, out, s)
}

func autoConvert_v1alpha1_Image_To_azure_Image(in *Image, out *azure.Image, s conversion.Scope) error {
	out.URN = (*string)(unsafe.Pointer(in.URN))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CommunityGalleryImageID = (*string)(unsafe.Pointer(in.CommunityGalleryImageID))
	out.SharedGalleryImageID = (*string)(unsafe.Pointer(in.SharedGalleryImageID))
	return nil
}

// Convert_v1alpha1_Image_To_azure_Image is an autogenerated conversion function.
func Convert_v1alpha1_Image_To_azure_Image(in *Image, out *azure.Image, s conversion.Scope) error {
	return autoConvert_v1alpha1_Image_To_azure_Image(in, out, s)
}

func autoConvert_azure_Image_To_v1alpha1_Image(in *azure.Image, out *Image, s conversion.Scope) error {
	out.URN = (*string)(unsafe.Pointer(in.URN))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CommunityGalleryImageID = (*string)(unsafe.Pointer(in.CommunityGalleryImageID))
	out.SharedGalleryImageID = (*string)(unsafe.Pointer(in.SharedGalleryImageID))
	return nil
}

// Convert_azure_Image_To_v1alpha1_Image is an autogenerated conversion function.
func Convert_azure_Image_To_v1alpha1_Image(in *azure.Image, out *Image, s conversion.Scope) error {
	return autoConvert_azure_Image_To_v1alpha1_Image(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_azure_InfrastructureConfig(in *InfrastructureConfig, out *azure.InfrastructureConfig, s conversion.Scope) error {
	out.ResourceGroup = (*azure.ResourceGroup)(unsafe.Pointer(in.ResourceGroup))
	if err := Convert_v1alpha1_NetworkConfig_To_azure_NetworkConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.Identity = (*azure.IdentityConfig)(unsafe.Pointer(in.Identity))
	out.Zoned = in.Zoned
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_azure_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_azure_InfrastructureConfig(in *InfrastructureConfig, out *azure.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_azure_InfrastructureConfig(in, out, s)
}

func autoConvert_azure_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *azure.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	out.ResourceGroup = (*ResourceGroup)(unsafe.Pointer(in.ResourceGroup))
	if err := Convert_azure_NetworkConfig_To_v1alpha1_NetworkConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.Identity = (*IdentityConfig)(unsafe.Pointer(in.Identity))
	out.Zoned = in.Zoned
	return nil
}

// Convert_azure_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_azure_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *azure.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_azure_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureState_To_azure_InfrastructureState(in *InfrastructureState, out *azure.InfrastructureState, s conversion.Scope) error {
	out.Data = *(*map[string]string)(unsafe.Pointer(&in.Data))
	out.ManagedItems = *(*[]azure.AzureResource)(unsafe.Pointer(&in.ManagedItems))
	return nil
}

// Convert_v1alpha1_InfrastructureState_To_azure_InfrastructureState is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureState_To_azure_InfrastructureState(in *InfrastructureState, out *azure.InfrastructureState, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureState_To_azure_InfrastructureState(in, out, s)
}

func autoConvert_azure_InfrastructureState_To_v1alpha1_InfrastructureState(in *azure.InfrastructureState, out *InfrastructureState, s conversion.Scope) error {
	out.Data = *(*map[string]string)(unsafe.Pointer(&in.Data))
	out.ManagedItems = *(*[]AzureResource)(unsafe.Pointer(&in.ManagedItems))
	return nil
}

// Convert_azure_InfrastructureState_To_v1alpha1_InfrastructureState is an autogenerated conversion function.
func Convert_azure_InfrastructureState_To_v1alpha1_InfrastructureState(in *azure.InfrastructureState, out *InfrastructureState, s conversion.Scope) error {
	return autoConvert_azure_InfrastructureState_To_v1alpha1_InfrastructureState(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_azure_InfrastructureStatus(in *InfrastructureStatus, out *azure.InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworkStatus_To_azure_NetworkStatus(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ResourceGroup_To_azure_ResourceGroup(&in.ResourceGroup, &out.ResourceGroup, s); err != nil {
		return err
	}
	out.AvailabilitySets = *(*[]azure.AvailabilitySet)(unsafe.Pointer(&in.AvailabilitySets))
	out.MigratingToVMO = in.MigratingToVMO
	out.RouteTables = *(*[]azure.RouteTable)(unsafe.Pointer(&in.RouteTables))
	out.SecurityGroups = *(*[]azure.SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	out.Identity = (*azure.IdentityStatus)(unsafe.Pointer(in.Identity))
	out.Zoned = in.Zoned
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_azure_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_azure_InfrastructureStatus(in *InfrastructureStatus, out *azure.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_azure_InfrastructureStatus(in, out, s)
}

func autoConvert_azure_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *azure.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_azure_NetworkStatus_To_v1alpha1_NetworkStatus(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	if err := Convert_azure_ResourceGroup_To_v1alpha1_ResourceGroup(&in.ResourceGroup, &out.ResourceGroup, s); err != nil {
		return err
	}
	out.AvailabilitySets = *(*[]AvailabilitySet)(unsafe.Pointer(&in.AvailabilitySets))
	out.MigratingToVMO = in.MigratingToVMO
	out.RouteTables = *(*[]RouteTable)(unsafe.Pointer(&in.RouteTables))
	out.SecurityGroups = *(*[]SecurityGroup)(unsafe.Pointer(&in.SecurityGroups))
	out.Identity = (*IdentityStatus)(unsafe.Pointer(in.Identity))
	out.Zoned = in.Zoned
	return nil
}

// Convert_azure_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_azure_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *azure.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_azure_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_azure_MachineImage(in *MachineImage, out *azure.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.AcceleratedNetworking = (*bool)(unsafe.Pointer(in.AcceleratedNetworking))
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	out.SkipMarketplaceAgreement = (*bool)(unsafe.Pointer(in.SkipMarketplaceAgreement))
	if err := Convert_v1alpha1_Image_To_azure_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_MachineImage_To_azure_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_azure_MachineImage(in *MachineImage, out *azure.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_azure_MachineImage(in, out, s)
}

func autoConvert_azure_MachineImage_To_v1alpha1_MachineImage(in *azure.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.AcceleratedNetworking = (*bool)(unsafe.Pointer(in.AcceleratedNetworking))
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	out.SkipMarketplaceAgreement = (*bool)(unsafe.Pointer(in.SkipMarketplaceAgreement))
	if err := Convert_azure_Image_To_v1alpha1_Image(&in.Image, &out.Image, s); err != nil {
		return err
	}
	return nil
}

// Convert_azure_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_azure_MachineImage_To_v1alpha1_MachineImage(in *azure.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_azure_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_azure_MachineImageVersion(in *MachineImageVersion, out *azure.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.URN = (*string)(unsafe.Pointer(in.URN))
	out.SkipMarketplaceAgreement = (*bool)(unsafe.Pointer(in.SkipMarketplaceAgreement))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CommunityGalleryImageID = (*string)(unsafe.Pointer(in.CommunityGalleryImageID))
	out.SharedGalleryImageID = (*string)(unsafe.Pointer(in.SharedGalleryImageID))
	out.AcceleratedNetworking = (*bool)(unsafe.Pointer(in.AcceleratedNetworking))
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_azure_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_azure_MachineImageVersion(in *MachineImageVersion, out *azure.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_azure_MachineImageVersion(in, out, s)
}

func autoConvert_azure_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *azure.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.URN = (*string)(unsafe.Pointer(in.URN))
	out.SkipMarketplaceAgreement = (*bool)(unsafe.Pointer(in.SkipMarketplaceAgreement))
	out.ID = (*string)(unsafe.Pointer(in.ID))
	out.CommunityGalleryImageID = (*string)(unsafe.Pointer(in.CommunityGalleryImageID))
	out.SharedGalleryImageID = (*string)(unsafe.Pointer(in.SharedGalleryImageID))
	out.AcceleratedNetworking = (*bool)(unsafe.Pointer(in.AcceleratedNetworking))
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_azure_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_azure_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *azure.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_azure_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_azure_MachineImages(in *MachineImages, out *azure.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]azure.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_azure_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_azure_MachineImages(in *MachineImages, out *azure.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_azure_MachineImages(in, out, s)
}

func autoConvert_azure_MachineImages_To_v1alpha1_MachineImages(in *azure.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_azure_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_azure_MachineImages_To_v1alpha1_MachineImages(in *azure.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_azure_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_MachineType_To_azure_MachineType(in *MachineType, out *azure.MachineType, s conversion.Scope) error {
	out.Name = in.Name
	out.AcceleratedNetworking = (*bool)(unsafe.Pointer(in.AcceleratedNetworking))
	return nil
}

// Convert_v1alpha1_MachineType_To_azure_MachineType is an autogenerated conversion function.
func Convert_v1alpha1_MachineType_To_azure_MachineType(in *MachineType, out *azure.MachineType, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineType_To_azure_MachineType(in, out, s)
}

func autoConvert_azure_MachineType_To_v1alpha1_MachineType(in *azure.MachineType, out *MachineType, s conversion.Scope) error {
	out.Name = in.Name
	out.AcceleratedNetworking = (*bool)(unsafe.Pointer(in.AcceleratedNetworking))
	return nil
}

// Convert_azure_MachineType_To_v1alpha1_MachineType is an autogenerated conversion function.
func Convert_azure_MachineType_To_v1alpha1_MachineType(in *azure.MachineType, out *MachineType, s conversion.Scope) error {
	return autoConvert_azure_MachineType_To_v1alpha1_MachineType(in, out, s)
}

func autoConvert_v1alpha1_NatGatewayConfig_To_azure_NatGatewayConfig(in *NatGatewayConfig, out *azure.NatGatewayConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IdleConnectionTimeoutMinutes = (*int32)(unsafe.Pointer(in.IdleConnectionTimeoutMinutes))
	out.Zone = (*int32)(unsafe.Pointer(in.Zone))
	out.IPAddresses = *(*[]azure.PublicIPReference)(unsafe.Pointer(&in.IPAddresses))
	return nil
}

// Convert_v1alpha1_NatGatewayConfig_To_azure_NatGatewayConfig is an autogenerated conversion function.
func Convert_v1alpha1_NatGatewayConfig_To_azure_NatGatewayConfig(in *NatGatewayConfig, out *azure.NatGatewayConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NatGatewayConfig_To_azure_NatGatewayConfig(in, out, s)
}

func autoConvert_azure_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(in *azure.NatGatewayConfig, out *NatGatewayConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IdleConnectionTimeoutMinutes = (*int32)(unsafe.Pointer(in.IdleConnectionTimeoutMinutes))
	out.Zone = (*int32)(unsafe.Pointer(in.Zone))
	out.IPAddresses = *(*[]PublicIPReference)(unsafe.Pointer(&in.IPAddresses))
	return nil
}

// Convert_azure_NatGatewayConfig_To_v1alpha1_NatGatewayConfig is an autogenerated conversion function.
func Convert_azure_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(in *azure.NatGatewayConfig, out *NatGatewayConfig, s conversion.Scope) error {
	return autoConvert_azure_NatGatewayConfig_To_v1alpha1_NatGatewayConfig(in, out, s)
}

func autoConvert_v1alpha1_NetworkConfig_To_azure_NetworkConfig(in *NetworkConfig, out *azure.NetworkConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_VNet_To_azure_VNet(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	out.Workers = (*string)(unsafe.Pointer(in.Workers))
	out.NatGateway = (*azure.NatGatewayConfig)(unsafe.Pointer(in.NatGateway))
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	out.Zones = *(*[]azure.Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_v1alpha1_NetworkConfig_To_azure_NetworkConfig is an autogenerated conversion function.
func Convert_v1alpha1_NetworkConfig_To_azure_NetworkConfig(in *NetworkConfig, out *azure.NetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkConfig_To_azure_NetworkConfig(in, out, s)
}

func autoConvert_azure_NetworkConfig_To_v1alpha1_NetworkConfig(in *azure.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	if err := Convert_azure_VNet_To_v1alpha1_VNet(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	out.Workers = (*string)(unsafe.Pointer(in.Workers))
	out.NatGateway = (*NatGatewayConfig)(unsafe.Pointer(in.NatGateway))
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	out.Zones = *(*[]Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_azure_NetworkConfig_To_v1alpha1_NetworkConfig is an autogenerated conversion function.
func Convert_azure_NetworkConfig_To_v1alpha1_NetworkConfig(in *azure.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	return autoConvert_azure_NetworkConfig_To_v1alpha1_NetworkConfig(in, out, s)
}

func autoConvert_v1alpha1_NetworkStatus_To_azure_NetworkStatus(in *NetworkStatus, out *azure.NetworkStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_VNetStatus_To_azure_VNetStatus(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	out.Subnets = *(*[]azure.Subnet)(unsafe.Pointer(&in.Subnets))
	out.Layout = azure.NetworkLayout(in.Layout)
	out.OutboundAccessType = azure.OutboundAccessType(in.OutboundAccessType)
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_azure_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_azure_NetworkStatus(in *NetworkStatus, out *azure.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_azure_NetworkStatus(in, out, s)
}

func autoConvert_azure_NetworkStatus_To_v1alpha1_NetworkStatus(in *azure.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	if err := Convert_azure_VNetStatus_To_v1alpha1_VNetStatus(&in.VNet, &out.VNet, s); err != nil {
		return err
	}
	out.Subnets = *(*[]Subnet)(unsafe.Pointer(&in.Subnets))
	out.Layout = NetworkLayout(in.Layout)
	out.OutboundAccessType = OutboundAccessType(in.OutboundAccessType)
	return nil
}

// Convert_azure_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_azure_NetworkStatus_To_v1alpha1_NetworkStatus(in *azure.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_azure_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_PublicIPReference_To_azure_PublicIPReference(in *PublicIPReference, out *azure.PublicIPReference, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.Zone = in.Zone
	return nil
}

// Convert_v1alpha1_PublicIPReference_To_azure_PublicIPReference is an autogenerated conversion function.
func Convert_v1alpha1_PublicIPReference_To_azure_PublicIPReference(in *PublicIPReference, out *azure.PublicIPReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_PublicIPReference_To_azure_PublicIPReference(in, out, s)
}

func autoConvert_azure_PublicIPReference_To_v1alpha1_PublicIPReference(in *azure.PublicIPReference, out *PublicIPReference, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	out.Zone = in.Zone
	return nil
}

// Convert_azure_PublicIPReference_To_v1alpha1_PublicIPReference is an autogenerated conversion function.
func Convert_azure_PublicIPReference_To_v1alpha1_PublicIPReference(in *azure.PublicIPReference, out *PublicIPReference, s conversion.Scope) error {
	return autoConvert_azure_PublicIPReference_To_v1alpha1_PublicIPReference(in, out, s)
}

func autoConvert_v1alpha1_ResourceGroup_To_azure_ResourceGroup(in *ResourceGroup, out *azure.ResourceGroup, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ResourceGroup_To_azure_ResourceGroup is an autogenerated conversion function.
func Convert_v1alpha1_ResourceGroup_To_azure_ResourceGroup(in *ResourceGroup, out *azure.ResourceGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceGroup_To_azure_ResourceGroup(in, out, s)
}

func autoConvert_azure_ResourceGroup_To_v1alpha1_ResourceGroup(in *azure.ResourceGroup, out *ResourceGroup, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_azure_ResourceGroup_To_v1alpha1_ResourceGroup is an autogenerated conversion function.
func Convert_azure_ResourceGroup_To_v1alpha1_ResourceGroup(in *azure.ResourceGroup, out *ResourceGroup, s conversion.Scope) error {
	return autoConvert_azure_ResourceGroup_To_v1alpha1_ResourceGroup(in, out, s)
}

func autoConvert_v1alpha1_RouteTable_To_azure_RouteTable(in *RouteTable, out *azure.RouteTable, s conversion.Scope) error {
	out.Purpose = azure.Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_RouteTable_To_azure_RouteTable is an autogenerated conversion function.
func Convert_v1alpha1_RouteTable_To_azure_RouteTable(in *RouteTable, out *azure.RouteTable, s conversion.Scope) error {
	return autoConvert_v1alpha1_RouteTable_To_azure_RouteTable(in, out, s)
}

func autoConvert_azure_RouteTable_To_v1alpha1_RouteTable(in *azure.RouteTable, out *RouteTable, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_azure_RouteTable_To_v1alpha1_RouteTable is an autogenerated conversion function.
func Convert_azure_RouteTable_To_v1alpha1_RouteTable(in *azure.RouteTable, out *RouteTable, s conversion.Scope) error {
	return autoConvert_azure_RouteTable_To_v1alpha1_RouteTable(in, out, s)
}

func autoConvert_v1alpha1_SecurityGroup_To_azure_SecurityGroup(in *SecurityGroup, out *azure.SecurityGroup, s conversion.Scope) error {
	out.Purpose = azure.Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_SecurityGroup_To_azure_SecurityGroup is an autogenerated conversion function.
func Convert_v1alpha1_SecurityGroup_To_azure_SecurityGroup(in *SecurityGroup, out *azure.SecurityGroup, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecurityGroup_To_azure_SecurityGroup(in, out, s)
}

func autoConvert_azure_SecurityGroup_To_v1alpha1_SecurityGroup(in *azure.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	out.Purpose = Purpose(in.Purpose)
	out.Name = in.Name
	return nil
}

// Convert_azure_SecurityGroup_To_v1alpha1_SecurityGroup is an autogenerated conversion function.
func Convert_azure_SecurityGroup_To_v1alpha1_SecurityGroup(in *azure.SecurityGroup, out *SecurityGroup, s conversion.Scope) error {
	return autoConvert_azure_SecurityGroup_To_v1alpha1_SecurityGroup(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_azure_Storage(in *Storage, out *azure.Storage, s conversion.Scope) error {
	out.ManagedDefaultStorageClass = (*bool)(unsafe.Pointer(in.ManagedDefaultStorageClass))
	out.ManagedDefaultVolumeSnapshotClass = (*bool)(unsafe.Pointer(in.ManagedDefaultVolumeSnapshotClass))
	return nil
}

// Convert_v1alpha1_Storage_To_azure_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_azure_Storage(in *Storage, out *azure.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_azure_Storage(in, out, s)
}

func autoConvert_azure_Storage_To_v1alpha1_Storage(in *azure.Storage, out *Storage, s conversion.Scope) error {
	out.ManagedDefaultStorageClass = (*bool)(unsafe.Pointer(in.ManagedDefaultStorageClass))
	out.ManagedDefaultVolumeSnapshotClass = (*bool)(unsafe.Pointer(in.ManagedDefaultVolumeSnapshotClass))
	return nil
}

// Convert_azure_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_azure_Storage_To_v1alpha1_Storage(in *azure.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_azure_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_Subnet_To_azure_Subnet(in *Subnet, out *azure.Subnet, s conversion.Scope) error {
	out.Name = in.Name
	out.Purpose = azure.Purpose(in.Purpose)
	out.Zone = (*string)(unsafe.Pointer(in.Zone))
	out.Migrated = in.Migrated
	out.NatGatewayID = (*string)(unsafe.Pointer(in.NatGatewayID))
	return nil
}

// Convert_v1alpha1_Subnet_To_azure_Subnet is an autogenerated conversion function.
func Convert_v1alpha1_Subnet_To_azure_Subnet(in *Subnet, out *azure.Subnet, s conversion.Scope) error {
	return autoConvert_v1alpha1_Subnet_To_azure_Subnet(in, out, s)
}

func autoConvert_azure_Subnet_To_v1alpha1_Subnet(in *azure.Subnet, out *Subnet, s conversion.Scope) error {
	out.Name = in.Name
	out.Purpose = Purpose(in.Purpose)
	out.Zone = (*string)(unsafe.Pointer(in.Zone))
	out.Migrated = in.Migrated
	out.NatGatewayID = (*string)(unsafe.Pointer(in.NatGatewayID))
	return nil
}

// Convert_azure_Subnet_To_v1alpha1_Subnet is an autogenerated conversion function.
func Convert_azure_Subnet_To_v1alpha1_Subnet(in *azure.Subnet, out *Subnet, s conversion.Scope) error {
	return autoConvert_azure_Subnet_To_v1alpha1_Subnet(in, out, s)
}

func autoConvert_v1alpha1_VNet_To_azure_VNet(in *VNet, out *azure.VNet, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	out.DDosProtectionPlanID = (*string)(unsafe.Pointer(in.DDosProtectionPlanID))
	return nil
}

// Convert_v1alpha1_VNet_To_azure_VNet is an autogenerated conversion function.
func Convert_v1alpha1_VNet_To_azure_VNet(in *VNet, out *azure.VNet, s conversion.Scope) error {
	return autoConvert_v1alpha1_VNet_To_azure_VNet(in, out, s)
}

func autoConvert_azure_VNet_To_v1alpha1_VNet(in *azure.VNet, out *VNet, s conversion.Scope) error {
	out.Name = (*string)(unsafe.Pointer(in.Name))
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	out.CIDR = (*string)(unsafe.Pointer(in.CIDR))
	out.DDosProtectionPlanID = (*string)(unsafe.Pointer(in.DDosProtectionPlanID))
	return nil
}

// Convert_azure_VNet_To_v1alpha1_VNet is an autogenerated conversion function.
func Convert_azure_VNet_To_v1alpha1_VNet(in *azure.VNet, out *VNet, s conversion.Scope) error {
	return autoConvert_azure_VNet_To_v1alpha1_VNet(in, out, s)
}

func autoConvert_v1alpha1_VNetStatus_To_azure_VNetStatus(in *VNetStatus, out *azure.VNetStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	return nil
}

// Convert_v1alpha1_VNetStatus_To_azure_VNetStatus is an autogenerated conversion function.
func Convert_v1alpha1_VNetStatus_To_azure_VNetStatus(in *VNetStatus, out *azure.VNetStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_VNetStatus_To_azure_VNetStatus(in, out, s)
}

func autoConvert_azure_VNetStatus_To_v1alpha1_VNetStatus(in *azure.VNetStatus, out *VNetStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = (*string)(unsafe.Pointer(in.ResourceGroup))
	return nil
}

// Convert_azure_VNetStatus_To_v1alpha1_VNetStatus is an autogenerated conversion function.
func Convert_azure_VNetStatus_To_v1alpha1_VNetStatus(in *azure.VNetStatus, out *VNetStatus, s conversion.Scope) error {
	return autoConvert_azure_VNetStatus_To_v1alpha1_VNetStatus(in, out, s)
}

func autoConvert_v1alpha1_VmoDependency_To_azure_VmoDependency(in *VmoDependency, out *azure.VmoDependency, s conversion.Scope) error {
	out.PoolName = in.PoolName
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_VmoDependency_To_azure_VmoDependency is an autogenerated conversion function.
func Convert_v1alpha1_VmoDependency_To_azure_VmoDependency(in *VmoDependency, out *azure.VmoDependency, s conversion.Scope) error {
	return autoConvert_v1alpha1_VmoDependency_To_azure_VmoDependency(in, out, s)
}

func autoConvert_azure_VmoDependency_To_v1alpha1_VmoDependency(in *azure.VmoDependency, out *VmoDependency, s conversion.Scope) error {
	out.PoolName = in.PoolName
	out.ID = in.ID
	out.Name = in.Name
	return nil
}

// Convert_azure_VmoDependency_To_v1alpha1_VmoDependency is an autogenerated conversion function.
func Convert_azure_VmoDependency_To_v1alpha1_VmoDependency(in *azure.VmoDependency, out *VmoDependency, s conversion.Scope) error {
	return autoConvert_azure_VmoDependency_To_v1alpha1_VmoDependency(in, out, s)
}

func autoConvert_v1alpha1_WorkerConfig_To_azure_WorkerConfig(in *WorkerConfig, out *azure.WorkerConfig, s conversion.Scope) error {
	out.NodeTemplate = (*extensionsv1alpha1.NodeTemplate)(unsafe.Pointer(in.NodeTemplate))
	out.DiagnosticsProfile = (*azure.DiagnosticsProfile)(unsafe.Pointer(in.DiagnosticsProfile))
	out.DataVolumes = *(*[]azure.DataVolume)(unsafe.Pointer(&in.DataVolumes))
	return nil
}

// Convert_v1alpha1_WorkerConfig_To_azure_WorkerConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkerConfig_To_azure_WorkerConfig(in *WorkerConfig, out *azure.WorkerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerConfig_To_azure_WorkerConfig(in, out, s)
}

func autoConvert_azure_WorkerConfig_To_v1alpha1_WorkerConfig(in *azure.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	out.NodeTemplate = (*extensionsv1alpha1.NodeTemplate)(unsafe.Pointer(in.NodeTemplate))
	out.DiagnosticsProfile = (*DiagnosticsProfile)(unsafe.Pointer(in.DiagnosticsProfile))
	out.DataVolumes = *(*[]DataVolume)(unsafe.Pointer(&in.DataVolumes))
	return nil
}

// Convert_azure_WorkerConfig_To_v1alpha1_WorkerConfig is an autogenerated conversion function.
func Convert_azure_WorkerConfig_To_v1alpha1_WorkerConfig(in *azure.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	return autoConvert_azure_WorkerConfig_To_v1alpha1_WorkerConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_azure_WorkerStatus(in *WorkerStatus, out *azure.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]azure.MachineImage)(unsafe.Pointer(&in.MachineImages))
	out.VmoDependencies = *(*[]azure.VmoDependency)(unsafe.Pointer(&in.VmoDependencies))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_azure_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_azure_WorkerStatus(in *WorkerStatus, out *azure.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_azure_WorkerStatus(in, out, s)
}

func autoConvert_azure_WorkerStatus_To_v1alpha1_WorkerStatus(in *azure.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	out.VmoDependencies = *(*[]VmoDependency)(unsafe.Pointer(&in.VmoDependencies))
	return nil
}

// Convert_azure_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_azure_WorkerStatus_To_v1alpha1_WorkerStatus(in *azure.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_azure_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}

func autoConvert_v1alpha1_WorkloadIdentityConfig_To_azure_WorkloadIdentityConfig(in *WorkloadIdentityConfig, out *azure.WorkloadIdentityConfig, s conversion.Scope) error {
	out.ClientID = in.ClientID
	out.TenantID = in.TenantID
	out.SubscriptionID = in.SubscriptionID
	return nil
}

// Convert_v1alpha1_WorkloadIdentityConfig_To_azure_WorkloadIdentityConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkloadIdentityConfig_To_azure_WorkloadIdentityConfig(in *WorkloadIdentityConfig, out *azure.WorkloadIdentityConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkloadIdentityConfig_To_azure_WorkloadIdentityConfig(in, out, s)
}

func autoConvert_azure_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(in *azure.WorkloadIdentityConfig, out *WorkloadIdentityConfig, s conversion.Scope) error {
	out.ClientID = in.ClientID
	out.TenantID = in.TenantID
	out.SubscriptionID = in.SubscriptionID
	return nil
}

// Convert_azure_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig is an autogenerated conversion function.
func Convert_azure_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(in *azure.WorkloadIdentityConfig, out *WorkloadIdentityConfig, s conversion.Scope) error {
	return autoConvert_azure_WorkloadIdentityConfig_To_v1alpha1_WorkloadIdentityConfig(in, out, s)
}

func autoConvert_v1alpha1_Zone_To_azure_Zone(in *Zone, out *azure.Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	out.NatGateway = (*azure.ZonedNatGatewayConfig)(unsafe.Pointer(in.NatGateway))
	return nil
}

// Convert_v1alpha1_Zone_To_azure_Zone is an autogenerated conversion function.
func Convert_v1alpha1_Zone_To_azure_Zone(in *Zone, out *azure.Zone, s conversion.Scope) error {
	return autoConvert_v1alpha1_Zone_To_azure_Zone(in, out, s)
}

func autoConvert_azure_Zone_To_v1alpha1_Zone(in *azure.Zone, out *Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.CIDR = in.CIDR
	out.ServiceEndpoints = *(*[]string)(unsafe.Pointer(&in.ServiceEndpoints))
	out.NatGateway = (*ZonedNatGatewayConfig)(unsafe.Pointer(in.NatGateway))
	return nil
}

// Convert_azure_Zone_To_v1alpha1_Zone is an autogenerated conversion function.
func Convert_azure_Zone_To_v1alpha1_Zone(in *azure.Zone, out *Zone, s conversion.Scope) error {
	return autoConvert_azure_Zone_To_v1alpha1_Zone(in, out, s)
}

func autoConvert_v1alpha1_ZonedNatGatewayConfig_To_azure_ZonedNatGatewayConfig(in *ZonedNatGatewayConfig, out *azure.ZonedNatGatewayConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IdleConnectionTimeoutMinutes = (*int32)(unsafe.Pointer(in.IdleConnectionTimeoutMinutes))
	out.IPAddresses = *(*[]azure.ZonedPublicIPReference)(unsafe.Pointer(&in.IPAddresses))
	return nil
}

// Convert_v1alpha1_ZonedNatGatewayConfig_To_azure_ZonedNatGatewayConfig is an autogenerated conversion function.
func Convert_v1alpha1_ZonedNatGatewayConfig_To_azure_ZonedNatGatewayConfig(in *ZonedNatGatewayConfig, out *azure.ZonedNatGatewayConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ZonedNatGatewayConfig_To_azure_ZonedNatGatewayConfig(in, out, s)
}

func autoConvert_azure_ZonedNatGatewayConfig_To_v1alpha1_ZonedNatGatewayConfig(in *azure.ZonedNatGatewayConfig, out *ZonedNatGatewayConfig, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.IdleConnectionTimeoutMinutes = (*int32)(unsafe.Pointer(in.IdleConnectionTimeoutMinutes))
	out.IPAddresses = *(*[]ZonedPublicIPReference)(unsafe.Pointer(&in.IPAddresses))
	return nil
}

// Convert_azure_ZonedNatGatewayConfig_To_v1alpha1_ZonedNatGatewayConfig is an autogenerated conversion function.
func Convert_azure_ZonedNatGatewayConfig_To_v1alpha1_ZonedNatGatewayConfig(in *azure.ZonedNatGatewayConfig, out *ZonedNatGatewayConfig, s conversion.Scope) error {
	return autoConvert_azure_ZonedNatGatewayConfig_To_v1alpha1_ZonedNatGatewayConfig(in, out, s)
}

func autoConvert_v1alpha1_ZonedPublicIPReference_To_azure_ZonedPublicIPReference(in *ZonedPublicIPReference, out *azure.ZonedPublicIPReference, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	return nil
}

// Convert_v1alpha1_ZonedPublicIPReference_To_azure_ZonedPublicIPReference is an autogenerated conversion function.
func Convert_v1alpha1_ZonedPublicIPReference_To_azure_ZonedPublicIPReference(in *ZonedPublicIPReference, out *azure.ZonedPublicIPReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ZonedPublicIPReference_To_azure_ZonedPublicIPReference(in, out, s)
}

func autoConvert_azure_ZonedPublicIPReference_To_v1alpha1_ZonedPublicIPReference(in *azure.ZonedPublicIPReference, out *ZonedPublicIPReference, s conversion.Scope) error {
	out.Name = in.Name
	out.ResourceGroup = in.ResourceGroup
	return nil
}

// Convert_azure_ZonedPublicIPReference_To_v1alpha1_ZonedPublicIPReference is an autogenerated conversion function.
func Convert_azure_ZonedPublicIPReference_To_v1alpha1_ZonedPublicIPReference(in *azure.ZonedPublicIPReference, out *ZonedPublicIPReference, s conversion.Scope) error {
	return autoConvert_azure_ZonedPublicIPReference_To_v1alpha1_ZonedPublicIPReference(in, out, s)
}
