apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: remedy-controller-azure
  namespace: {{ .Release.Namespace }}
  labels:
    app: remedy-controller-azure
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: remedy-controller-azure
  unhealthyPodEvictionPolicy: AlwaysAllow
