{{- if semverCompare ">= 1.21-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: remedy-controller-azure
  namespace: {{ .Release.Namespace }}
  labels:
    app: remedy-controller-azure
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: remedy-controller-azure
