apiVersion: v1
kind: ServiceAccount
metadata:
  name: remedy-controller-azure
  namespace: {{ .Release.Namespace }}
{{- if .Values.global.useProjectedTokenMount }}
automountServiceAccountToken: false
{{- end }}
