name: Release
on:
  workflow_dispatch:
    inputs:
      next-version:
        description: 'Select the type of version bump for the next release.'
        type: choice
        options:
          - bump-minor
          - bump-patch
      release-version:
        description: 'Select whether to modify the release version.'
        type: choice
        options:
          - noop
          - set-prerelease

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    with:
      mode: release
      release-version: ${{ inputs.release-version }}

  integration-tests:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/run-integrationtests.yaml

  release-to-github-and-bump:
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build
      - integration-tests
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    with:
      release-commit-target: branch
      next-version: ${{ inputs.next-version }}
      next-version-callback-action-path: .github/actions/prepare-release
      slack-channel-id: C9CEBQPGE # #sap-tech-gardener
