{{- range .Values.servicePrincipals }}
---
apiVersion: v1
kind: Secret
metadata:
  name: service-principal-{{ print .tenantID .clientID .clientSecret | sha256sum | trunc 12 }}
  namespace: {{ $.Release.Namespace }}
  labels:
    azure.provider.extensions.gardener.cloud/purpose: tenant-service-principal-secret
data:
  tenantID: {{ .tenantID }}
  clientID: {{ .clientID }}
  clientSecret: {{ .clientSecret }}
type: Opaque
{{- end }}
